# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchtower', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='event',
            field=models.TextField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
