# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchtower', '0003_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborhood',
            name='event',
        ),
    ]
