# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchtower', '0006_auto_20180526_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='neighborhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_parastatal', to='watchtower.Neighborhood'),
        ),
    ]
