# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchtower', '0008_post_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='neighborhood',
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='event',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
