# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchtower', '0009_auto_20180526_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='no_occupants',
            field=models.IntegerField(null=True),
        ),
    ]
