# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchtower', '0012_business_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Business',
            new_name='Establishment',
        ),
    ]
