# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchtower', '0014_auto_20180528_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
